k8s_yaml(local(
  'mise exec -- kluctl render -t kind --include-tag kind --print-all'
))

k8s_resource('cert-manager', 
  objects=[
    'cert-manager:namespace',
    'cert-manager-webhook:mutatingwebhookconfiguration', 
    'cert-manager-webhook:validatingwebhookconfiguration',
    # CRDs
    'certificaterequests.cert-manager.io',
    'certificates.cert-manager.io',
    'challenges.acme.cert-manager.io',
    'clusterissuers.cert-manager.io',
    'issuers.cert-manager.io',
    'orders.acme.cert-manager.io',
    # Namespace scoped resources 
    'cert-manager-cainjector:serviceaccount',
    'cert-manager:serviceaccount',
    'cert-manager-cainjector\\:leaderelection:role',
    'cert-manager\\:leaderelection:role',
    'cert-manager-tokenrequest:role',
    'cert-manager-startupapicheck\\:create-cert:role',
    'cert-manager-cainjector\\:leaderelection:rolebinding',
    'cert-manager\\:leaderelection:rolebinding',
    'cert-manager-tokenrequest:rolebinding',
    'cert-manager-startupapicheck\\:create-cert:rolebinding'
  ],
  labels=['cert-manager']
)
k8s_resource('cert-manager-webhook', 
  objects=[
    'cert-manager-webhook:serviceaccount',
    'cert-manager-webhook\\:dynamic-serving:role',
    'cert-manager-webhook\\:dynamic-serving:rolebinding'
  ], 
  labels=['cert-manager']
)
local_resource('cert-manager-webhook-wait', 
  cmd='kubectl wait --namespace cert-manager --for=condition=ready pod -l app.kubernetes.io/component=webhook --timeout=120s',
  resource_deps=['cert-manager-webhook'],
  labels=['cert-manager']
)
k8s_resource(
  new_name='cert-manager-resources', 
  objects=[
    'letsencrypt-prod-dns:clusterissuer',
    'letsencrypt-staging-dns:clusterissuer',
    'selfsigned:clusterissuer'
  ], 
  resource_deps=['cert-manager-webhook-wait'],
  labels=['cert-manager']
)
k8s_resource('cert-manager-startupapicheck', 
  objects=['cert-manager-startupapicheck:serviceaccount'], 
  labels=['cert-manager']
)
k8s_resource('cert-manager-cainjector', 
  objects=[], 
  labels=['cert-manager']
)


###
k8s_resource('cloudnative-pg', 
  objects=[
    'cnpg-system:namespace',
    'cloudnative-pg:serviceaccount',
    'cnpg-mutating-webhook-configuration:mutatingwebhookconfiguration', 
    'cnpg-validating-webhook-configuration:validatingwebhookconfiguration',
    'backups.postgresql.cnpg.io',
    'clusterimagecatalogs.postgresql.cnpg.io',
    'clusters.postgresql.cnpg.io',
    'databases.postgresql.cnpg.io',
    'failoverquorums.postgresql.cnpg.io',
    'imagecatalogs.postgresql.cnpg.io',
    'poolers.postgresql.cnpg.io',
    'publications.postgresql.cnpg.io',
    'scheduledbackups.postgresql.cnpg.io',
    'subscriptions.postgresql.cnpg.io',
    'cnpg-controller-manager-config:configmap',
    'cnpg-default-monitoring:configmap'
  ],
  resource_deps=['cert-manager'], 
  labels=['cloudnative-pg']
)
local_resource('cloudnative-pg-wait', 
  cmd='kubectl wait --namespace cnpg-system --for=condition=ready pod -l app.kubernetes.io/instance=cloudnative-pg --timeout=120s',
  resource_deps=['cloudnative-pg'],
  labels=['cloudnative-pg']
)
k8s_kind('clusters.postgresql.cnpg.io', 
  image_json_path='{.spec.imageName}',
  pod_readiness='wait'
)

