# go-backend-timoni

# Docker images are built in go-backend/Tiltfile (shared across all variants)

k8s_yaml(
  local(
    'timoni build go-backend . -n go-backend-timoni --values values.yaml --values values.local.yaml',
    quiet=True
  )
)

k8s_resource(
  workload='go-backend:deployment:go-backend-timoni',
  new_name='go-backend-timoni',
  labels=['go-backend-timoni'],
  resource_deps=['cloudnative-pg']
)
k8s_resource(
  workload='go-backend-migrate:job:go-backend-timoni',
  new_name='go-backend-timoni-migrate',
  labels=['go-backend-timoni'],
  resource_deps=['cloudnative-pg']
)
