docker_build(
  '857059614049.dkr.ecr.us-east-2.amazonaws.com/services/go-backend-no-migrations', 
  '../../../../services/go-backend-no-migrations'
)

k8s_resource('go-backend-no-migrations', 
  port_forwards='8081:8080', # TODO: establish local port mapping conventions
  objects=[
    'minimal-nginx-2:ingress'
  ],
  resource_deps=[
    'ingress-nginx-wait'
  ],
  labels=['go-backend-no-migrations']
)