# This is used by the action https://github.com/dorny/paths-filter

# This is effectively serving as a naive target determinator (see: https://blog.swgillespie.me/posts/monorepo-ingredients/)

# ---- services ---------------------------------------------------------------
services/go-backend: &go_backend
  - "services/go-backend/**"
  - ".github/workflows/build_push.yml" # build on change to this workflow
  - ".github/utils/file-filters.yaml" # build on filter change

services/go-backend/migrator:
  - *go_backend # db migrations tied to service

services/container-only-dummy:
  - "services/container-only-dummy/**"
