version: "3"

tasks:
  generate-version:
    desc: "Use git describe to generate a tag based on the latest release tag"
    vars:
      SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
    cmds:
      - |
        set -euo pipefail
        TAG=$(git describe --tags --always --first-parent --match "{{.SERVICE_RELEASE_TAG}}@[0-9]*.[0-9]*.[0-9]*")
        PREFIX="{{.SERVICE_RELEASE_TAG}}@"
        echo "${TAG#${PREFIX}}"
    silent: true

  generate-version-tag:
    desc: "Combine the image repo with the version tag"
    vars:
      SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
      VERSION:
        sh: task -s generate-version -- {{.SERVICE_RELEASE_TAG}}
    cmds:
      - |
        echo "{{.IMAGE_REPO}}:{{.VERSION}}"

  generate-extended-version:
    desc: "If commits since last tag: emit next-patch pre x.y.(z+1)-N-g<sha>; else: x.y.z"
    vars:
      SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
      BASE_VERSION:
        sh: task -s generate-version -- {{.SERVICE_RELEASE_TAG}}
    cmds:
      - |
        set -euo pipefail

        BASE="{{.BASE_VERSION}}"   # e.g., 1.2.3 or 1.2.3-7-gabc123
        # Ensure we have -N-g<sha> suffix for counting commits
        if [[ ! $BASE =~ -g[0-9a-fA-F]+$ ]]; then
          GIT_HASH="$(git rev-parse --short HEAD)"
          BASE="${BASE}-0-g${GIT_HASH}"
        fi

        IFS='-' read -r CORE COUNT GREF <<<"$BASE"

        if [[ "$COUNT" -eq 0 ]]; then
          # exactly at the tag: emit the clean release number
          echo "$CORE"
          exit 0
        fi

        # bump patch: x.y.(z+1)
        IFS='.' read -r MA MI PA <<<"$CORE"
        NEXT_PATCH=$((PA+1))
        CORE_NEXT="${MA}.${MI}.${NEXT_PATCH}"

        # pre-release/release candidate count zero-padded and keep git ref for traceability
        printf "%s-rc%04d-%s\n" "$CORE_NEXT" "$COUNT" "$GREF"
    silent: true

  generate-extended-version-tag:
    desc: "Combine the image repo with the version tag"
    vars:
      SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
      VERSION:
        sh: task -s generate-extended-version -- {{.SERVICE_RELEASE_TAG}}
    cmds:
      - |
        echo "{{.IMAGE_REPO}}:{{.VERSION}}"

  manual-version-tag:
    desc: "Combine the image repo with the input version tag"
    vars:
      VERSION: "{{.CLI_ARGS}}"
    cmds:
      - |
        echo "{{.IMAGE_REPO}}:{{.VERSION}}"
