# Apply these manually with kluctl (ordering of things matters more)
include('../../kubernetes/kluctl/infrastructure/Tiltfile')

include('../../kubernetes/kluctl/apps/Tiltfile')

k8s_yaml('../kind/Service.dockerhost.yaml')