# Apply these manually with kluctl (ordering of things matters more)
include('../../kubernetes/src/infrastructure/Tiltfile')

include('../../kubernetes/src/services/Tiltfile')

k8s_yaml('../kind/Service.dockerhost.yaml')