issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:DevOps-Directive/kube-starter-kit:.*
claim_pattern:
  # ⚠️ NOTE: using '^DevOps-Directive/kube-starter-kit/\.github/workflows/digger.*' did not match
  workflow_ref: '^DevOps-Directive/kube-starter-kit/\.github/workflows/digger.*@refs/.*$'

permissions:
  # For Terraform
  administration: write # repo permission
  metadata: read # repo permission
  members: write # org permission
  # For Digger
  contents: write # required to merge PRs
  actions: write # required for plan persistence
  pull_requests: write # required to post PR comments
  issues: write # required to check if PR number is an issue or not (and write to it for drift detection)
  statuses: write # required to validate combined PR status
