issuer: https://token.actions.githubusercontent.com
# TODO: restrict
subject: repo:my-org/my-repo:.*

permissions:
  administration: write # repo permission
  metadata: read # repo permission
  members: read # org permission
