issuer: https://token.actions.githubusercontent.com
# TODO: restrict
subject_pattern: repo:DevOps-Directive/kube-starter-kit:.*

permissions:
  administration: write # repo permission
  metadata: read # repo permission
  members: read # org permission
