issuer: https://token.actions.githubusercontent.com
subject: repo:DevOps-Directive/kube-starter-kit:ref:refs/heads/main

permissions:
  contents: write # read commits and create tags
  pull_requests: write # create/edit PRs
