issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:DevOps-Directive/kube-starter-kit:.*
claim_pattern:
  workflow_ref: '^DevOps-Directive/kube-starter-kit/\.github/workflows/terramate.*@refs/.*$'

permissions:
  # For Terraform
  administration: write # repo permission
  metadata: read # repo permission
  members: write # org permission
  # For Terramate workflows
  contents: read # required to checkout code
